### PR TITLE
Add three main game: squad, playerPerWin and squad

### PR DESCRIPTION
**Pull request by MKoth**

### CODE REVIEW

**Comment by walkwel** [comment]
Hey @MKoth,

There are few lint issues in the PR that you have sent. Can you quickly fix those?
Run `yarn lint` command to see the list of lint issues.

**Comment by MKoth** [comment]
Just did, seems check passed

**Comment by walkwel** [comment]
Thank you Michael for that.

Can you also confirm below, 
I have checked that you have modified the code for Gem Collector Game.
https://walkwel.github.io/ALSET-reactGame-ui/
Can you kindly check Gem Collector game here and confirm you haven't edited this one.

Note :
- There are two Gem Collectors, 'Gem Collector' & 'Squad Gem Collector' currently.

So just want to confirm its not overwritten in your PR.

Thank you.

**Comment by MKoth** [comment]
I guess it is overwritten, both of those are the same game, so I thought there is no need for one, if there is, I can bring it back

**Comment by MKoth** [comment]
Also there is new game, called Passenger pickup, it can be added to the list

**Comment by walkwel** [comment]
Yes, Kindly bring it back that one is also required. I have seen the new game. It's looks perfect for me. Once you fixed this GemCollector, I will merge the PR straightaway.

**Comment by MKoth** [comment]
Hi, the old gemCollector is back, new gemCollector is called squadGemCollector

**Pull request merged**
